"""The Windows install path the broker hands a recipient.

A Windows user's first contact with Dispatch is a command copied off the
install page. Until ``/install.ps1`` existed, the only thing offered was a bash
one-liner, which a stock Windows machine cannot run — onboarding ended there,
with no error to search for.

These tests guard the two ways that can silently regress:

  1. **The route stops being reachable.** The broker mounts StaticFiles at
     ``/``; a route registered after that mount is shadowed and 404s. The mount
     happens at import time at the bottom of the module, so this is a real
     ordering hazard rather than a theoretical one.

  2. **The script stops being valid PowerShell.** It is generated by f-string
     interpolation into a language where ``{`` and ``}`` are block delimiters,
     so every brace has to be doubled. Miss one and the broker still returns
     200 with a body that fails to parse on the user's machine — the failure
     surfaces on someone else's computer, not in CI.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys

import pytest
from fastapi.testclient import TestClient

os.environ.setdefault("DISPATCH_JWT_SECRET", "test-secret-" + "x" * 32)

from dispatch.broker.app import app  # noqa: E402

client = TestClient(app)


def test_the_powershell_installer_is_served():
    resp = client.get("/install.ps1")
    assert resp.status_code == 200, "shadowed by the StaticFiles mount at /"
    assert "charset=utf-8" in resp.headers["content-type"]
    assert resp.text.lstrip().startswith("#Requires -Version 5.1")


def test_both_installers_are_offered():
    """Neither platform may lose its installer while the other keeps one."""
    assert client.get("/install.sh").status_code == 200
    assert client.get("/install.ps1").status_code == 200


def test_the_installer_carries_the_broker_and_spec():
    body = client.get("/install.ps1").text
    assert "$Broker      = '" in body
    assert "$InstallSpec = '" in body
    # The token is supplied by the user, never baked in.
    assert "$Token" in body


def test_the_installer_writes_config_owner_only():
    """A chmod would be a no-op here, so the script must set an ACL.

    ~/.dispatch/config.json holds a broker bearer JWT. On Windows a new file
    inherits the profile ACL, which every administrator can read.
    """
    body = client.get("/install.ps1").text
    assert "icacls" in body
    assert "/inheritance:r" in body


def test_the_installer_does_not_trust_a_bare_python_on_path():
    """Stock Windows 11 ships a python.exe app-execution alias that is a stub
    opening the Microsoft Store. Presence on PATH proves nothing, so the script
    has to probe for a working interpreter."""
    body = client.get("/install.ps1").text
    assert "function Get-Python" in body
    assert "sys.version_info" in body


@pytest.mark.skipif(sys.platform != "win32", reason="needs Windows PowerShell")
def test_the_generated_script_is_valid_powershell(tmp_path):
    """Parse the real generated text with the real parser.

    This is the check that cannot be faked by reading the source: the f-string
    braces have to survive interpolation, and only a parser knows.
    """
    powershell = (
        os.path.join(
            os.environ.get("SystemRoot", r"C:\Windows"),
            "System32", "WindowsPowerShell", "v1.0", "powershell.exe",
        )
    )
    if not os.path.exists(powershell):
        powershell = shutil.which("powershell") or ""
    if not powershell:
        pytest.skip("no powershell.exe found")

    script = tmp_path / "install.ps1"
    script.write_text(client.get("/install.ps1").text, encoding="utf-8")

    probe = (
        "$e=$null; $t=$null;"
        "[System.Management.Automation.Language.Parser]::ParseFile("
        f"'{script}', [ref]$t, [ref]$e) | Out-Null;"
        "if ($e -and $e.Count) { $e | ForEach-Object { $_.Message }; exit 1 };"
        "exit 0"
    )
    result = subprocess.run(
        [powershell, "-NoProfile", "-NonInteractive", "-Command", probe],
        capture_output=True, text=True, timeout=120,
    )
    assert result.returncode == 0, f"PowerShell parse errors:\n{result.stdout}"
