// Google Material icons, re-exported under the names the app already uses (the
// old lucide names) so call sites stay unchanged — only the import path moves
// from "lucide-react" to "@/lib/icons". One place to remap or restyle icons.
//
// react-icons/md renders <svg> components that take className/size just like
// lucide did, so `className="size-4"` etc. keep working.
export {
  MdErrorOutline as AlertCircle,
  MdArrowBack as ArrowLeft,
  MdArrowUpward as ArrowUp,
  MdBlock as Ban,
  MdNotifications as Bell,
  MdMenuBook as BookText,
  MdSmartToy as Bot,
  MdDataObject as Braces,
  MdPsychology as Brain,
  MdCalendarToday as Calendar,
  MdEventNote as CalendarClock,
  MdTextFields as CaseSensitive,
  MdCheck as Check,
  MdCheckCircle as CheckCircle,
  MdKeyboardArrowDown as ChevronDown,
  MdKeyboardArrowRight as ChevronRight,
  MdAccessTime as Clock,
  MdCode as Code,
  MdContentCopy as Copy,
  MdReply as CornerUpLeft,
  MdCasino as Dices,
  MdInput as FileInput,
  MdOutput as FileOutput,
  MdDescription as FileText,
  MdFilterList as Filter,
  MdSpeed as Gauge,
  MdCallSplit as GitBranch,
  MdPublic as Globe,
  MdTag as Hash,
  MdHistory as History,
  MdInbox as Inbox,
  MdAllInclusive as Infinity,
  MdKey as KeyRound,
  MdAccountTree as ListTree,
  MdSync as Loader2,
  MdLock as Lock,
  MdMail as Mails,
  MdMergeType as Merge,
  MdChatBubbleOutline as MessageSquare,
  MdDesktopWindows as Monitor,
  MdAttachFile as Paperclip,
  MdPause as Pause,
  MdEdit as Pencil,
  MdPlayArrow as Play,
  MdAdd as Plus,
  MdManageSearch as Regex,
  MdRefresh as RotateCcw,
  MdRoute as Route,
  MdSave as Save,
  MdDocumentScanner as ScanText,
  MdSearch as Search,
  MdDns as Server,
  MdSettings as Settings,
  MdRemoveModerator as ShieldOff,
  MdFunctions as Sigma,
  MdTune as SlidersHorizontal,
  MdSmartphone as Smartphone,
  MdCropSquare as Square,
  MdLabel as Tags,
  MdDeleteOutline as Trash2,
  MdWarningAmber as TriangleAlert,
  MdTitle as Type,
  MdHowToReg as UserCheck,
  MdPersonAdd as UserPlus,
  MdGroup as Users,
  MdPersonOff as UserX,
  MdDataArray as Variable,
  MdVolumeUp as Volume2,
  MdSchema as Workflow,
  MdClose as X,
} from "react-icons/md";

export type { IconType as LucideIcon } from "react-icons";
